//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteMusicBand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomUsers()
        {
            this.News = new HashSet<News>();
            this.NewsComments = new HashSet<NewsComments>();
            this.NewsLikes = new HashSet<NewsLikes>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string AvatarLink { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ForumName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsComments> NewsComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsLikes> NewsLikes { get; set; }
    }
}
