//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteMusicBand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumMessagesInPost
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public int ForumPostID { get; set; }
        public string TextContent { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ForumPost ForumPost { get; set; }
    }
}
