//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteMusicBand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForumPost()
        {
            this.ForumMessagesInPosts = new HashSet<ForumMessagesInPost>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int ForumSectionId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumMessagesInPost> ForumMessagesInPosts { get; set; }
        public virtual ForumSection ForumSection { get; set; }
    }
}
