//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteMusicBand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsAdditionalInfo
    {
        public int NewsId { get; set; }
        public string Info { get; set; }
    
        public virtual News News { get; set; }
    }
}
