//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteMusicBand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Track()
        {
            this.TracksInPlaylists = new HashSet<TracksInPlaylists>();
        }
    
        public int TrackId { get; set; }
        public int AlbumId { get; set; }
        public string NameOfTrack { get; set; }
        public int Position { get; set; }
        public string TrackLink { get; set; }
    
        public virtual Album Albums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TracksInPlaylists> TracksInPlaylists { get; set; }
    }
}
