//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteMusicBand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int TrackId { get; set; }
        public int AlbumId { get; set; }
        public string NameOfTrack { get; set; }
        public int Position { get; set; }
        public string TrackLink { get; set; }
    
        public virtual Album Albums { get; set; }
    }
}
